#!/bin/bash
# /etc/init.d/gpioserver

### BEGIN INIT INFO
# Provides:          gpioserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting gpioserver"
        /var/www/gpio/GPIOServer.sh &
        ;;
    stop)
        echo "Stopping gpioserver"
        killall GPIOServer.sh
        ;;
    *)
        echo "Usage: /etc/init.d/gpioserver start|stop"
        exit 1
        ;;
esac

exit 0
