#!/bin/bash
# /etc/init.d/gpioserver

### BEGIN INIT INFO
# Provides:          gpioserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage GPIOServer.sh
### END INIT INFO

set -e

# Directory where web files are stored.
workdir=''

source /lib/lsb/init-functions

scriptloc="$workdir/GPIOServer.sh"

case "$1" in
    start)
		log_daemon_msg "Starting GPIO Server" "GPIOServer.sh" || true
		$scriptloc &
		if pgrep GPIOServer.sh >/dev/null 2>&1
		then
			log_end_msg 0 || true
		else
			log_end_msg 1 || true
		fi
        ;;
    stop)
		killall GPIOServer.sh && sleep 2
		if pgrep GPIOServer.sh >/dev/null 2>&1
		then
			echo "Stopping GPIO Server: FAIL"
		else
			echo "Stopping GPIO Server: Stopped"
		fi
        ;;
    restart)
		killall GPIOServer.sh && sleep 2
		if pgrep GPIOServer.sh >/dev/null 2>&1
		then
			echo "Stopping GPIO Server: FAIL"
		else
			echo "Stopping GPIO Server: Stopped"
		fi
		log_daemon_msg "Starting GPIO Server" "GPIOServer.sh" || true
		$scriptloc &
        ;;
	status)
		if pgrep GPIOServer.sh >/dev/null 2>&1
		then
			echo "GPIO Server status: Started"
		else
			echo "GPIO Server status: Stopped"
		fi
		;;
    *)
	log_action_msg "Usage: /etc/init.d/gpioserver {start|stop|restart|status}" || true
        exit 1
        ;;
esac

exit 0
